#!/bin/bash -ex

# This script starts docker and (on el7) systemd and runs a test

if [[ "$OS_TYPE" = "centos" ]] && [[ "$OS_VERSION" = "6" ]]; then
    sudo docker run --privileged --rm=true -v "$(pwd)":/build:rw centos:"$OS_VERSION" /bin/bash -exc "cd /build;.travis/build_test $OS_TYPE $OS_VERSION"
    exit
fi

# Mount /var/run/docker.sock and set --network=host so we can call docker from inside
# cause some tests need it. Cannot mount to /var/run/docker.sock inside cause CentOS
# /usr/sbin/init mounts another overlayfs on top of it
docker run --privileged -d -ti -e "container=docker" -v /var/run/docker.sock:/docker.sock --network=host \
    -v /sys/fs/cgroup:/sys/fs/cgroup -v "$(pwd)":/build:rw  "$OS_TYPE":"$OS_VERSION"   /usr/sbin/init
DOCKER_CONTAINER_ID=$(docker ps | grep "$OS_TYPE" | awk '{print $1}')
docker logs "$DOCKER_CONTAINER_ID"
docker exec -ti "$DOCKER_CONTAINER_ID" /bin/bash -exc "
    export DOCKER_HOST=unix:///docker.sock
    chmod o+rw /docker.sock &&
    cd /build &&
    .travis/build_test $OS_TYPE $OS_VERSION
"
docker ps -a
docker stop "$DOCKER_CONTAINER_ID"
docker rm -v "$DOCKER_CONTAINER_ID"
