#!/bin/bash -ex

# this script runs as root under docker

# shellcheck source=/dev/null

deps_file=".travis/deps/${OS_TYPE}_${OS_VERSION}_deps"

if [[ -e "${deps_file}" ]]; then
    source "${deps_file}"
else
    echo "OS ${OS_TYPE}, version ${OS_VERSION} not supported yet, please create ${deps_file}!"
    exit 1
fi

echo "%_var /var" > /root/.rpmmacros
echo "%_dbpath %{_var}/lib/rpm" >> /root/.rpmmacros

# build and install
install_autogen_deps
./autogen.sh

# the final spec file is only created after configure, but we need it before to
# parse it for build dependencies.
sed 's/@PACKAGE_VERSION@/0/' < singularity.spec.in > singularity_tmp.spec

install_configure_deps
./configure
make dist
rpmbuild -ta *.tar.gz

install_rpms

if [ "$OS_VERSION" = 6 ]; then
    echo "the test suite has not yet been ported to centos6 python, skipping."
    exit
fi

install_test_deps

# run the test suite
.travis/testsuite_run
