#!/bin/bash -ex

case $OS_TYPE in
    "") .travis/install_test ;;
    centos) .travis/rpmdist_run ;;
    debian) .travis/debian_run ;;
    opensuse) .travis/rpmdist_run ;;
    *) echo "Unknown OS_TYPE $OS_TYPE"; exit 1;;
esac
